version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/apps/app-router'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/apps/pages-router'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/packages/rollup-library'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/packages/rollup-flow-library'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/test-apps/rollup-library-app-router'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/test-apps/rollup-library-pages-test'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/test-apps/rollup-flow-library-app-router'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'

  - package-ecosystem: 'npm'
    directory: '/test-apps/rollup-flow-library-pages-router'
    schedule:
      interval: 'weekly'
    target-branch: 'feature-dependabot'
